/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

/**
 *
 * @author cg3034186
 */
public class AnalytcPopupGUI extends javax.swing.JDialog {

    /**
     * Creates new form AnalytcPopupGUI
     */
    public AnalytcPopupGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogContentPanel = new javax.swing.JPanel();
        calcPanel = new javax.swing.JPanel();
        calcHeader = new javax.swing.JPanel();
        calcConfigLabel = new javax.swing.JLabel();
        calcBody = new javax.swing.JPanel();
        sumBalancesTggleBtn = new javax.swing.JToggleButton();
        groupPanel = new javax.swing.JPanel();
        groupHeader = new javax.swing.JPanel();
        groupConfigLabel = new javax.swing.JLabel();
        groupBody = new javax.swing.JPanel();
        groupWithBalanceTggleBtn = new javax.swing.JToggleButton();
        filterPanel = new javax.swing.JPanel();
        filterHeader = new javax.swing.JPanel();
        filterConfigLabel = new javax.swing.JLabel();
        filterBody = new javax.swing.JPanel();
        HighAccountsFilterTggleBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogContentPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        calcPanel.setLayout(new java.awt.BorderLayout());

        calcConfigLabel.setText("Calc Config");
        calcHeader.add(calcConfigLabel);

        calcPanel.add(calcHeader, java.awt.BorderLayout.PAGE_START);

        sumBalancesTggleBtn.setText("Sum Balances");
        calcBody.add(sumBalancesTggleBtn);

        calcPanel.add(calcBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(calcPanel);

        groupPanel.setLayout(new java.awt.BorderLayout());

        groupConfigLabel.setText("Group Config");
        groupHeader.add(groupConfigLabel);

        groupPanel.add(groupHeader, java.awt.BorderLayout.PAGE_START);

        groupWithBalanceTggleBtn.setText("Group with Balance");
        groupWithBalanceTggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupWithBalanceTggleBtnActionPerformed(evt);
            }
        });
        groupBody.add(groupWithBalanceTggleBtn);

        groupPanel.add(groupBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(groupPanel);

        filterPanel.setLayout(new java.awt.BorderLayout());

        filterConfigLabel.setText("Filter Config");
        filterHeader.add(filterConfigLabel);

        filterPanel.add(filterHeader, java.awt.BorderLayout.PAGE_START);

        HighAccountsFilterTggleBtn.setText(">10000 Balance");
        HighAccountsFilterTggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighAccountsFilterTggleBtnActionPerformed(evt);
            }
        });
        filterBody.add(HighAccountsFilterTggleBtn);

        filterPanel.add(filterBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(filterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HighAccountsFilterTggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighAccountsFilterTggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HighAccountsFilterTggleBtnActionPerformed

    private void groupWithBalanceTggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupWithBalanceTggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupWithBalanceTggleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnalytcPopupGUI dialog = new AnalytcPopupGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton HighAccountsFilterTggleBtn;
    private javax.swing.JPanel calcBody;
    private javax.swing.JLabel calcConfigLabel;
    private javax.swing.JPanel calcHeader;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JPanel dialogContentPanel;
    private javax.swing.JPanel filterBody;
    private javax.swing.JLabel filterConfigLabel;
    private javax.swing.JPanel filterHeader;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel groupBody;
    private javax.swing.JLabel groupConfigLabel;
    private javax.swing.JPanel groupHeader;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JToggleButton groupWithBalanceTggleBtn;
    private javax.swing.JToggleButton sumBalancesTggleBtn;
    // End of variables declaration//GEN-END:variables
}
