/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.model.Account;
import br.com.bank.stategy.enumstrategy.AccountListStatesStrategy;
import br.com.bank.stategy.comparator.AccountListComparators;
import br.com.bank.stategy.predicate.AccountListPredicates;
import java.lang.reflect.Field;
import java.util.function.Predicate;
import java.util.Comparator;
import javax.swing.*;

/**
 *
 * @author cg3034186
 */

public final class AnalytcPopupGUI extends javax.swing.JDialog {

    private final AccountListStatesStrategy stateList;

    /**
     * Creates new form AnalytcPopupGUI
     */
    public AnalytcPopupGUI(java.awt.Frame parent, boolean modal, AccountListStatesStrategy stateList) {
        super(parent, modal);
        this.stateList = stateList;
        initComponents();
        setLocationRelativeTo(null);

        createDynamicPredicateButtons();
        createDynamicComparatorButtons();
    }

private void createDynamicPredicateButtons() {
    try {
        for (Field field : AccountListPredicates.class.getDeclaredFields()) {
            if (Predicate.class.isAssignableFrom(field.getType())) {
                String name = field.getName();
                JToggleButton btn = new JToggleButton(name);

                btn.setSelected(stateList.isPredicateActive(
                        (Predicate<Account>) field.get(null)
                ));

                btn.addActionListener(e -> {
                    try {
                        Predicate<Account> predicate = (Predicate<Account>) field.get(null);
                        stateList.togglePredicate(predicate);
                    } catch (IllegalAccessException ex) {
                        ex.printStackTrace();
                    }
                });

                filterBody.add(btn);
            }
        }
        filterBody.revalidate();
        filterBody.repaint();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void createDynamicComparatorButtons() {
    try {
        for (Field field : AccountListComparators.class.getDeclaredFields()) {
            if (Comparator.class.isAssignableFrom(field.getType())) {
                String name = field.getName();
                JToggleButton btn = new JToggleButton(name);

                btn.setSelected(stateList.isComparatorActive(
                        (Comparator<Account>) field.get(null)
                ));

                btn.addActionListener(e -> {
                    try {
                        Comparator<Account> comp = (Comparator<Account>) field.get(null);
                        stateList.toggleComparator(comp);
                    } catch (IllegalAccessException ex) {
                        ex.printStackTrace();
                    }
                });

                groupBody.add(btn);
            }
        }
        groupBody.revalidate();
        groupBody.repaint();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogContentPanel = new javax.swing.JPanel();
        groupPanel = new javax.swing.JPanel();
        groupHeader = new javax.swing.JPanel();
        groupConfigLabel = new javax.swing.JLabel();
        groupBody = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        filterHeader = new javax.swing.JPanel();
        filterConfigLabel = new javax.swing.JLabel();
        filterBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogContentPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        groupPanel.setLayout(new java.awt.BorderLayout());

        groupConfigLabel.setText("Comparators");
        groupHeader.add(groupConfigLabel);

        groupPanel.add(groupHeader, java.awt.BorderLayout.PAGE_START);
        groupPanel.add(groupBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(groupPanel);

        filterPanel.setLayout(new java.awt.BorderLayout());

        filterConfigLabel.setText("Predicates");
        filterHeader.add(filterConfigLabel);

        filterPanel.add(filterHeader, java.awt.BorderLayout.PAGE_START);
        filterPanel.add(filterBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(filterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dialogContentPanel;
    private javax.swing.JPanel filterBody;
    private javax.swing.JLabel filterConfigLabel;
    private javax.swing.JPanel filterHeader;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel groupBody;
    private javax.swing.JLabel groupConfigLabel;
    private javax.swing.JPanel groupHeader;
    private javax.swing.JPanel groupPanel;
    // End of variables declaration//GEN-END:variables
}
