/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.stategy.enumstrategy.AccountListStatesStrategy;
import br.com.bank.stategy.comparator.AccountListComparators;
import br.com.bank.stategy.predicate.AccountListPredicates;

/**
 *
 * @author cg3034186
 */
public class AnalytcPopupGUI extends javax.swing.JDialog {
    private final AccountListStatesStrategy stateList;
    
    

    /**
     * Creates new form AnalytcPopupGUI
     */
    public AnalytcPopupGUI(java.awt.Frame parent, boolean modal, AccountListStatesStrategy stateList) {
        super(parent, modal);
        this.stateList = stateList;
        initComponents();
        
        setLocationRelativeTo(null);
        highAccountsFilterTggleBtn.setSelected(stateList.isPredicateActive(AccountListPredicates.BALANCE_OVER_5000));
        groupWithBalanceTggleBtn.setSelected(stateList.isComparatorActive(AccountListComparators.ORDER_BY_BALANCE_DESC));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogContentPanel = new javax.swing.JPanel();
        groupPanel = new javax.swing.JPanel();
        groupHeader = new javax.swing.JPanel();
        groupConfigLabel = new javax.swing.JLabel();
        groupBody = new javax.swing.JPanel();
        groupWithBalanceTggleBtn = new javax.swing.JToggleButton();
        filterPanel = new javax.swing.JPanel();
        filterHeader = new javax.swing.JPanel();
        filterConfigLabel = new javax.swing.JLabel();
        filterBody = new javax.swing.JPanel();
        highAccountsFilterTggleBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogContentPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        groupPanel.setLayout(new java.awt.BorderLayout());

        groupConfigLabel.setText("Group Config");
        groupHeader.add(groupConfigLabel);

        groupPanel.add(groupHeader, java.awt.BorderLayout.PAGE_START);

        groupWithBalanceTggleBtn.setText("Group with Balance");
        groupWithBalanceTggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupWithBalanceTggleBtnActionPerformed(evt);
            }
        });
        groupBody.add(groupWithBalanceTggleBtn);

        groupPanel.add(groupBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(groupPanel);

        filterPanel.setLayout(new java.awt.BorderLayout());

        filterConfigLabel.setText("Filter Config");
        filterHeader.add(filterConfigLabel);

        filterPanel.add(filterHeader, java.awt.BorderLayout.PAGE_START);

        highAccountsFilterTggleBtn.setText(">10000 Balance");
        highAccountsFilterTggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highAccountsFilterTggleBtnActionPerformed(evt);
            }
        });
        filterBody.add(highAccountsFilterTggleBtn);

        filterPanel.add(filterBody, java.awt.BorderLayout.CENTER);

        dialogContentPanel.add(filterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void highAccountsFilterTggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highAccountsFilterTggleBtnActionPerformed
        stateList.togglePredicate(AccountListPredicates.BALANCE_OVER_5000);
    }//GEN-LAST:event_highAccountsFilterTggleBtnActionPerformed

    private void groupWithBalanceTggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupWithBalanceTggleBtnActionPerformed
        stateList.toggleComparator(AccountListComparators.ORDER_BY_BALANCE_DESC);
    }//GEN-LAST:event_groupWithBalanceTggleBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dialogContentPanel;
    private javax.swing.JPanel filterBody;
    private javax.swing.JLabel filterConfigLabel;
    private javax.swing.JPanel filterHeader;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel groupBody;
    private javax.swing.JLabel groupConfigLabel;
    private javax.swing.JPanel groupHeader;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JToggleButton groupWithBalanceTggleBtn;
    private javax.swing.JToggleButton highAccountsFilterTggleBtn;
    // End of variables declaration//GEN-END:variables
}
