/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.exceptions.InvalidInputException;
import br.com.bank.model.Bank;
import br.com.bank.service.AccountService;
import br.com.bank.service.BankService;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class CreateAccountGUI extends javax.swing.JDialog {

    private final Bank bank;
    private final AccountService accountService;

    /**
     * Creates new form CreateAccountGUI
     */
    public CreateAccountGUI(java.awt.Frame parent, boolean modal, Bank bank, AccountService accountService, BankService bankService) {
        super(parent, modal);
        this.bank = bank;
        this.accountService = accountService;
        initComponents();
        getRootPane().registerKeyboardAction(
                e -> dispose(),
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCreateAccount = new javax.swing.JPanel();
        SavingToggleBtn = new javax.swing.JToggleButton();
        PayrollToggleBtn = new javax.swing.JToggleButton();
        CurrentToggleBtn = new javax.swing.JToggleButton();
        labelBalance1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtBalance = new javax.swing.JTextField();
        labelBalance = new javax.swing.JLabel();
        txtHolder = new javax.swing.JTextField();
        labekHolder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");
        setResizable(false);
        setSize(new java.awt.Dimension(480, 360));

        SavingToggleBtn.setText("Saving");
        SavingToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingToggleBtnActionPerformed(evt);
            }
        });

        PayrollToggleBtn.setText("Payroll");
        PayrollToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollToggleBtnActionPerformed(evt);
            }
        });

        CurrentToggleBtn.setText("Current");
        CurrentToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentToggleBtnActionPerformed(evt);
            }
        });

        labelBalance1.setText("type");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelBalance.setText("Initial Balance");

        txtHolder.setColumns(20);
        txtHolder.setToolTipText("");
        txtHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHolderActionPerformed(evt);
            }
        });

        labekHolder.setText("Holder");

        javax.swing.GroupLayout painelCreateAccountLayout = new javax.swing.GroupLayout(painelCreateAccount);
        painelCreateAccount.setLayout(painelCreateAccountLayout);
        painelCreateAccountLayout.setHorizontalGroup(
            painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCreateAccountLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCreateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CurrentToggleBtn)
                .addGap(24, 24, 24)
                .addComponent(SavingToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PayrollToggleBtn)
                .addContainerGap())
            .addGroup(painelCreateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCreateAccountLayout.createSequentialGroup()
                        .addComponent(labelBalance)
                        .addGap(35, 35, 35)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelCreateAccountLayout.createSequentialGroup()
                        .addComponent(labekHolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCreateAccountLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        painelCreateAccountLayout.setVerticalGroup(
            painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCreateAccountLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labekHolder)
                    .addComponent(txtHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavingToggleBtn)
                    .addComponent(PayrollToggleBtn)
                    .addComponent(labelBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentToggleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(painelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelCreateAccountLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHolderActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String holder_txt = txtHolder.getText().trim();
        String balance_txt = txtBalance.getText().trim();
        boolean current = CurrentToggleBtn.isSelected();
        boolean saving = SavingToggleBtn.isSelected();
        boolean payroll = PayrollToggleBtn.isSelected();

        Boolean[] states = {current, saving, payroll};
        long count = Arrays.stream(states).filter(b -> b).count();

        if ( holder_txt.isEmpty() || balance_txt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pleas fill in the all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (count > 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pleas select one type of Account", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double balance = Double.parseDouble(balance_txt);
        String type;

        if (current) {
            type = "CURRENT";
        } else if (saving) {
            type = "SAVING";
        } else if (payroll) {
            type = "PAYROLL";
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please, the type of the account have to be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            boolean result = accountService.createAccount(bank, holder_txt, balance, type);

            if (result) {
                JOptionPane.showMessageDialog(this,
                        "Account created successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                txtHolder.setText("");
                txtBalance.setText("");
                CurrentToggleBtn.setSelected(false);
                SavingToggleBtn.setSelected(false);
                PayrollToggleBtn.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this,
                        "The account could not be created. Try again.",
                        "Warning",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error during create account, invalid inputs: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error during create account, error when inserting in the bank: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void CurrentToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentToggleBtnActionPerformed

    private void PayrollToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayrollToggleBtnActionPerformed

    private void SavingToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavingToggleBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CurrentToggleBtn;
    private javax.swing.JToggleButton PayrollToggleBtn;
    private javax.swing.JToggleButton SavingToggleBtn;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel labekHolder;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelBalance1;
    private javax.swing.JPanel painelCreateAccount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtHolder;
    // End of variables declaration//GEN-END:variables
}
