/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.dao.AccountDAO;
import br.com.bank.exceptions.InsufficientBalanceException;
import br.com.bank.exceptions.InvalidInputException;
import br.com.bank.model.Account;
import br.com.bank.model.Bank;
import br.com.bank.service.AccountService;
import br.com.bank.service.BankService;
import br.com.bank.stategy.enumstrategy.AccountListStatesStrategy;
import java.io.IOException;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author cg3034186
 */
public class EditAccountGUI extends javax.swing.JDialog {

    private final Bank bank;
    private final ListAccountsGUI list;
    public AccountListStatesStrategy statesList;
    private final Account account;
    private final AccountService accountService;
    private final BankService bankService;
    private int accountId;
    private String holder;
    private double balance;

    public EditAccountGUI(java.awt.Frame parent, boolean modal, Account account, Bank bank, BankService bankService, AccountService accountService, ListAccountsGUI list, AccountListStatesStrategy statesList) {
        super(parent, modal);
        this.bank = bank;
        this.account = account;
        this.bankService = bankService;
        this.accountService = accountService;
        this.list = list;
        this.statesList = statesList;
        initComponents();
        setLocationRelativeTo(null);

        try {
            this.holder = accountService.getHolder(account);
            this.accountId = accountService.getId(account);
            this.balance = accountService.getBalance(account);

        } catch (InvalidInputException e) {
            JOptionPane.showMessageDialog(this, "Error in get the account informations: " + e.getMessage(), "informations account Error", JOptionPane.ERROR_MESSAGE);
        }

        accountIdTxt.setText(String.valueOf(accountId));
        holderTxt.setText(String.valueOf(holder));
        atualBalanceTxt.setText(String.valueOf(balance));

    }

    public void refreshBalanceAccountInformation(BigDecimal newBalance) {
        atualBalanceTxt.setText(String.valueOf(newBalance));

    }

    public void refreshAccountInformation(Account account) throws InvalidInputException {
        AccountDAO accountDAO = new AccountDAO();
        Account dbAccount = accountDAO.getAccount(accountService.getId(account));
        this.balance = accountService.getBalance(dbAccount);
        holderTxt.setText(String.valueOf(accountService.getHolder(account)));
        atualBalanceTxt.setText(String.valueOf(accountService.getBalance(dbAccount)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        VoltarBtn = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        Editcontainer = new javax.swing.JPanel();
        accountInformationsPanel = new javax.swing.JPanel();
        accountInformationsHeader = new javax.swing.JPanel();
        accountInformationsLabel = new javax.swing.JLabel();
        accountInformationsContent = new javax.swing.JPanel();
        accountIdLabel = new javax.swing.JLabel();
        atualBalanceLabel = new javax.swing.JLabel();
        holderLabel = new javax.swing.JLabel();
        holderTxt = new javax.swing.JTextArea();
        accountIdTxt = new javax.swing.JTextArea();
        atualBalanceTxt = new javax.swing.JTextArea();
        ExcluirContaBtn = new javax.swing.JButton();
        operationsInAccountPanel = new javax.swing.JPanel();
        withdrawPanel = new javax.swing.JPanel();
        withdrawHeader = new javax.swing.JPanel();
        withdrawLabel = new javax.swing.JLabel();
        withdrawContent = new javax.swing.JPanel();
        insertAmountLabel = new javax.swing.JLabel();
        withdrawAmountTxt = new javax.swing.JTextField();
        withdrawConfirmBtn = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        depositHeader = new javax.swing.JPanel();
        depositLabel = new javax.swing.JLabel();
        depositContent = new javax.swing.JPanel();
        depositAmountLabel = new javax.swing.JLabel();
        depositAmountTxt = new javax.swing.JTextField();
        depositConfirmBtn = new javax.swing.JButton();
        TransactionContainer = new javax.swing.JPanel();
        TransactionHeader = new javax.swing.JPanel();
        titleTranactionLabel = new javax.swing.JLabel();
        withdrawHeader1 = new javax.swing.JPanel();
        TransactionTitleLabel = new javax.swing.JLabel();
        insertAccountIdLabel1 = new javax.swing.JPanel();
        insertAmountLabel1 = new javax.swing.JLabel();
        TransactionIdAccountTxt = new javax.swing.JTextField();
        TransactionConfirmBtn1 = new javax.swing.JButton();
        TransactionAmountTxt = new javax.swing.JTextField();
        insertAmountLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        Header.setLayout(new java.awt.FlowLayout(0, 10, 10));

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });
        Header.add(VoltarBtn);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Center.setLayout(new java.awt.GridLayout(2, 2));

        Editcontainer.setLayout(new java.awt.GridLayout(1, 0));

        accountInformationsPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(0, 30, 5);
        flowLayout1.setAlignOnBaseline(true);
        accountInformationsHeader.setLayout(flowLayout1);

        accountInformationsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountInformationsLabel.setText("Account Informations:");
        accountInformationsHeader.add(accountInformationsLabel);

        accountInformationsPanel.add(accountInformationsHeader, java.awt.BorderLayout.PAGE_START);

        accountIdLabel.setText("Account ID:");

        atualBalanceLabel.setText("Atual Balance");

        holderLabel.setText("Holder");

        holderTxt.setEditable(false);
        holderTxt.setColumns(20);
        holderTxt.setRows(5);
        holderTxt.setEnabled(false);

        accountIdTxt.setEditable(false);
        accountIdTxt.setColumns(20);
        accountIdTxt.setRows(5);
        accountIdTxt.setEnabled(false);

        atualBalanceTxt.setEditable(false);
        atualBalanceTxt.setColumns(20);
        atualBalanceTxt.setRows(5);
        atualBalanceTxt.setEnabled(false);

        ExcluirContaBtn.setText("Excluir Conta");
        ExcluirContaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirContaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountInformationsContentLayout = new javax.swing.GroupLayout(accountInformationsContent);
        accountInformationsContent.setLayout(accountInformationsContentLayout);
        accountInformationsContentLayout.setHorizontalGroup(
            accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationsContentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirContaBtn)
                    .addGroup(accountInformationsContentLayout.createSequentialGroup()
                        .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountIdLabel)
                            .addComponent(holderLabel)
                            .addComponent(atualBalanceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(holderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountInformationsContentLayout.setVerticalGroup(
            accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationsContentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountIdLabel)
                    .addComponent(accountIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(holderLabel)
                    .addComponent(holderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualBalanceLabel)
                    .addComponent(atualBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ExcluirContaBtn)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        accountInformationsPanel.add(accountInformationsContent, java.awt.BorderLayout.CENTER);

        Editcontainer.add(accountInformationsPanel);

        operationsInAccountPanel.setLayout(new java.awt.GridLayout(2, 0));

        withdrawPanel.setLayout(new java.awt.BorderLayout());

        withdrawHeader.setLayout(new java.awt.FlowLayout(0));

        withdrawLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        withdrawLabel.setText("Withdraw");
        withdrawHeader.add(withdrawLabel);

        withdrawPanel.add(withdrawHeader, java.awt.BorderLayout.PAGE_START);

        insertAmountLabel.setText("Insert Amount");

        withdrawConfirmBtn.setText("Withdraw");
        withdrawConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawContentLayout = new javax.swing.GroupLayout(withdrawContent);
        withdrawContent.setLayout(withdrawContentLayout);
        withdrawContentLayout.setHorizontalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawContentLayout.createSequentialGroup()
                        .addComponent(insertAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(withdrawConfirmBtn)))
                .addContainerGap())
        );
        withdrawContentLayout.setVerticalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertAmountLabel)
                    .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawConfirmBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        withdrawPanel.add(withdrawContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(withdrawPanel);

        depositPanel.setLayout(new java.awt.BorderLayout());

        depositHeader.setLayout(new java.awt.FlowLayout(0));

        depositLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositLabel.setText("Deposit");
        depositHeader.add(depositLabel);

        depositPanel.add(depositHeader, java.awt.BorderLayout.PAGE_START);

        depositAmountLabel.setText("Insert Amount");

        depositConfirmBtn.setText("Deposit");
        depositConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositContentLayout = new javax.swing.GroupLayout(depositContent);
        depositContent.setLayout(depositContentLayout);
        depositContentLayout.setHorizontalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositContentLayout.createSequentialGroup()
                        .addComponent(depositAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depositConfirmBtn)))
                .addContainerGap())
        );
        depositContentLayout.setVerticalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAmountLabel)
                    .addComponent(depositAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositConfirmBtn)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        depositPanel.add(depositContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(depositPanel);

        Editcontainer.add(operationsInAccountPanel);

        Center.add(Editcontainer);

        TransactionContainer.setLayout(new java.awt.BorderLayout());

        TransactionHeader.setLayout(new java.awt.FlowLayout(0));

        titleTranactionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleTranactionLabel.setText("Deposit for an other account");
        TransactionHeader.add(titleTranactionLabel);

        TransactionContainer.add(TransactionHeader, java.awt.BorderLayout.PAGE_START);

        withdrawHeader1.setLayout(new java.awt.FlowLayout(0));

        TransactionTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransactionTitleLabel.setText("Deposit for other account");
        withdrawHeader1.add(TransactionTitleLabel);

        TransactionContainer.add(withdrawHeader1, java.awt.BorderLayout.PAGE_START);

        insertAmountLabel1.setText("Insert the Account number:");

        TransactionIdAccountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionIdAccountTxtActionPerformed(evt);
            }
        });

        TransactionConfirmBtn1.setText("Deposit");
        TransactionConfirmBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionConfirmBtn1ActionPerformed(evt);
            }
        });

        insertAmountLabel2.setText("Insert an amount to deposit");

        javax.swing.GroupLayout insertAccountIdLabel1Layout = new javax.swing.GroupLayout(insertAccountIdLabel1);
        insertAccountIdLabel1.setLayout(insertAccountIdLabel1Layout);
        insertAccountIdLabel1Layout.setHorizontalGroup(
            insertAccountIdLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertAccountIdLabel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertAccountIdLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertAccountIdLabel1Layout.createSequentialGroup()
                        .addComponent(insertAmountLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TransactionIdAccountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertAccountIdLabel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TransactionConfirmBtn1))
                    .addGroup(insertAccountIdLabel1Layout.createSequentialGroup()
                        .addComponent(insertAmountLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TransactionAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)))
                .addContainerGap())
        );
        insertAccountIdLabel1Layout.setVerticalGroup(
            insertAccountIdLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertAccountIdLabel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(insertAccountIdLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertAmountLabel1)
                    .addComponent(TransactionIdAccountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(insertAccountIdLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertAmountLabel2)
                    .addComponent(TransactionAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TransactionConfirmBtn1)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        TransactionContainer.add(insertAccountIdLabel1, java.awt.BorderLayout.CENTER);

        Center.add(TransactionContainer);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void withdrawConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawConfirmBtnActionPerformed
        double amount = Double.parseDouble(withdrawAmountTxt.getText());

        try {
            double newBalance = accountService.withdraw(account, bank, amount, bankService);
            refreshBalanceAccountInformation(new BigDecimal(newBalance));
        } catch (InsufficientBalanceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Insuficient Balance Error", JOptionPane.ERROR_MESSAGE);
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Value Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_withdrawConfirmBtnActionPerformed

    private void depositConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositConfirmBtnActionPerformed
        double amount = Double.parseDouble(depositAmountTxt.getText());
        try {
            double newBalance = accountService.deposit(account, bank, amount, bankService);
            refreshBalanceAccountInformation(new BigDecimal(newBalance));
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Value Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_depositConfirmBtnActionPerformed

    private void ExcluirContaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirContaBtnActionPerformed
        try {
            bankService.removeAccount(bank, accountService.getId(account));
        } catch (InvalidInputException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "we can't remove this account, try again later" + e.getMessage(),
                    "Run error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        dispose();
        list.initializer(statesList);
    }//GEN-LAST:event_ExcluirContaBtnActionPerformed

    private void TransactionConfirmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionConfirmBtn1ActionPerformed
        AccountDAO accountDao = new AccountDAO();
        Account receiver_account = null;
        try {
            receiver_account = bankService.searchAccount(bank, Integer.parseInt(TransactionIdAccountTxt.getText()));
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "we can't find the bank in the operation, try again later..." + ex.getMessage(),
                    "Run error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        try {
            boolean result = accountDao.transferForAccount(
                    account,
                    receiver_account,
                    new BigDecimal(TransactionAmountTxt.getText())
            );
            if (result == true) {
                JOptionPane.showMessageDialog(
                        null,
                        "transaction is done!!",
                        "Transaction error",
                        JOptionPane.DEFAULT_OPTION
                );
                bankService.refreshBankFromdb(bank);
                refreshAccountInformation(account);
                list.initializer(statesList);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "we can't do the transaction... " + e.getMessage(),
                    "Transaction error",
                    JOptionPane.ERROR_MESSAGE
            );

        }

    }//GEN-LAST:event_TransactionConfirmBtn1ActionPerformed

    private void TransactionIdAccountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionIdAccountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionIdAccountTxtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Editcontainer;
    private javax.swing.JButton ExcluirContaBtn;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField TransactionAmountTxt;
    private javax.swing.JButton TransactionConfirmBtn1;
    private javax.swing.JPanel TransactionContainer;
    private javax.swing.JPanel TransactionHeader;
    private javax.swing.JTextField TransactionIdAccountTxt;
    private javax.swing.JLabel TransactionTitleLabel;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JTextArea accountIdTxt;
    private javax.swing.JPanel accountInformationsContent;
    private javax.swing.JPanel accountInformationsHeader;
    private javax.swing.JLabel accountInformationsLabel;
    private javax.swing.JPanel accountInformationsPanel;
    private javax.swing.JLabel atualBalanceLabel;
    private javax.swing.JTextArea atualBalanceTxt;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JTextField depositAmountTxt;
    private javax.swing.JButton depositConfirmBtn;
    private javax.swing.JPanel depositContent;
    private javax.swing.JPanel depositHeader;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JLabel holderLabel;
    private javax.swing.JTextArea holderTxt;
    private javax.swing.JPanel insertAccountIdLabel1;
    private javax.swing.JLabel insertAmountLabel;
    private javax.swing.JLabel insertAmountLabel1;
    private javax.swing.JLabel insertAmountLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel operationsInAccountPanel;
    private javax.swing.JLabel titleTranactionLabel;
    private javax.swing.JTextField withdrawAmountTxt;
    private javax.swing.JButton withdrawConfirmBtn;
    private javax.swing.JPanel withdrawContent;
    private javax.swing.JPanel withdrawHeader;
    private javax.swing.JPanel withdrawHeader1;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
