/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

/**
 *
 * @author cg3034186
 */
public class AnalytcPopupGUI extends javax.swing.JDialog {

    /**
     * Creates new form AnalytcPopupGUI
     */
    public AnalytcPopupGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterPanel = new javax.swing.JPanel();
        filterHeader = new javax.swing.JPanel();
        filterConfigLabel = new javax.swing.JLabel();
        filterBody = new javax.swing.JPanel();
        groupPanel = new javax.swing.JPanel();
        groupHeader = new javax.swing.JPanel();
        groupConfigLabel = new javax.swing.JLabel();
        groupBody = new javax.swing.JPanel();
        calcPanel = new javax.swing.JPanel();
        calcHeader = new javax.swing.JPanel();
        calcConfigLabel = new javax.swing.JLabel();
        calcBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        filterPanel.setLayout(new java.awt.BorderLayout());

        filterConfigLabel.setText("Filter Config");
        filterHeader.add(filterConfigLabel);

        filterPanel.add(filterHeader, java.awt.BorderLayout.PAGE_START);

        filterBody.setLayout(new java.awt.GridBagLayout());
        filterPanel.add(filterBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(filterPanel, java.awt.BorderLayout.LINE_START);

        groupPanel.setLayout(new java.awt.BorderLayout());

        groupConfigLabel.setText("Calc Config");
        groupHeader.add(groupConfigLabel);

        groupPanel.add(groupHeader, java.awt.BorderLayout.PAGE_START);

        groupBody.setLayout(new java.awt.GridLayout());
        groupPanel.add(groupBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(groupPanel, java.awt.BorderLayout.LINE_END);

        calcPanel.setLayout(new java.awt.BorderLayout());

        calcConfigLabel.setText("Group Config");
        calcHeader.add(calcConfigLabel);

        calcPanel.add(calcHeader, java.awt.BorderLayout.PAGE_START);

        calcBody.setLayout(new java.awt.GridLayout());
        calcPanel.add(calcBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(calcPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalytcPopupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnalytcPopupGUI dialog = new AnalytcPopupGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calcBody;
    private javax.swing.JLabel calcConfigLabel;
    private javax.swing.JPanel calcHeader;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JPanel filterBody;
    private javax.swing.JLabel filterConfigLabel;
    private javax.swing.JPanel filterHeader;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel groupBody;
    private javax.swing.JLabel groupConfigLabel;
    private javax.swing.JPanel groupHeader;
    private javax.swing.JPanel groupPanel;
    // End of variables declaration//GEN-END:variables
}
