/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.exceptions.InsufficientBalanceException;
import br.com.bank.exceptions.InvalidInputException;
import br.com.bank.model.AccountCurrent;
import br.com.bank.model.Bank;
import br.com.bank.service.AccountService;
import br.com.bank.service.BankService;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cg3034186
 */
public class EditAccountGUI extends javax.swing.JDialog {

    private final Bank bank;
    private final AccountCurrent account;
    private final AccountService accountService;
    private final BankService bankService;
    private int accountId;
    private String holder;
    private double balance;

    public EditAccountGUI(java.awt.Frame parent, boolean modal, AccountCurrent account, Bank bank, BankService bankService, AccountService accountService) {
        super(parent, modal);
        this.bank = bank;
        this.account = account;
        this.bankService = bankService;
        this.accountService = accountService;
        initComponents();

        try {
            this.holder = accountService.getHolder(account);
            this.accountId = accountService.getId(account);
            this.balance = accountService.getBalance(account);

        } catch (InvalidInputException e) {
            JOptionPane.showMessageDialog(this, "Error in get the account informations: " + e.getMessage(), "informations account Error", JOptionPane.ERROR_MESSAGE);
        }

        accountIdTxt.setText(String.valueOf(accountId));
        holderTxt.setText(String.valueOf(holder));
        atualBalanceTxt.setText(String.valueOf(balance));

    }

    public void refreshAccountInformations(double newBalance) {
        atualBalanceTxt.setText(String.valueOf(newBalance));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        VoltarBtn = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        accountInformationsPanel = new javax.swing.JPanel();
        accountInformationsHeader = new javax.swing.JPanel();
        accountInformationsLabel = new javax.swing.JLabel();
        accountInformationsContent = new javax.swing.JPanel();
        accountIdLabel = new javax.swing.JLabel();
        atualBalanceLabel = new javax.swing.JLabel();
        holderLabel = new javax.swing.JLabel();
        holderTxt = new javax.swing.JTextArea();
        accountIdTxt = new javax.swing.JTextArea();
        atualBalanceTxt = new javax.swing.JTextArea();
        operationsInAccountPanel = new javax.swing.JPanel();
        withdrawPanel = new javax.swing.JPanel();
        withdrawHeader = new javax.swing.JPanel();
        withdrawLabel = new javax.swing.JLabel();
        withdrawContent = new javax.swing.JPanel();
        insertAmountLabel = new javax.swing.JLabel();
        withdrawAmountTxt = new javax.swing.JTextField();
        withdrawConfirmBtn = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        depositHeader = new javax.swing.JPanel();
        depositLabel = new javax.swing.JLabel();
        depositContent = new javax.swing.JPanel();
        depositAmountLabel = new javax.swing.JLabel();
        depositAmountTxt = new javax.swing.JTextField();
        depositConfirmBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });
        Header.add(VoltarBtn);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Center.setLayout(new java.awt.GridLayout(2, 2));

        container.setLayout(new java.awt.GridLayout(1, 0));

        accountInformationsPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5);
        flowLayout1.setAlignOnBaseline(true);
        accountInformationsHeader.setLayout(flowLayout1);

        accountInformationsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountInformationsLabel.setText("Account Informations:");
        accountInformationsHeader.add(accountInformationsLabel);

        accountInformationsPanel.add(accountInformationsHeader, java.awt.BorderLayout.PAGE_START);

        accountIdLabel.setText("Account ID:");

        atualBalanceLabel.setText("Atual Balance");

        holderLabel.setText("Holder");

        holderTxt.setEditable(false);
        holderTxt.setColumns(20);
        holderTxt.setRows(5);
        holderTxt.setEnabled(false);

        accountIdTxt.setEditable(false);
        accountIdTxt.setColumns(20);
        accountIdTxt.setRows(5);
        accountIdTxt.setEnabled(false);

        atualBalanceTxt.setEditable(false);
        atualBalanceTxt.setColumns(20);
        atualBalanceTxt.setRows(5);
        atualBalanceTxt.setEnabled(false);

        javax.swing.GroupLayout accountInformationsContentLayout = new javax.swing.GroupLayout(accountInformationsContent);
        accountInformationsContent.setLayout(accountInformationsContentLayout);
        accountInformationsContentLayout.setHorizontalGroup(
            accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationsContentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountIdLabel)
                    .addComponent(holderLabel)
                    .addComponent(atualBalanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(holderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountInformationsContentLayout.setVerticalGroup(
            accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationsContentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountIdLabel)
                    .addComponent(accountIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(holderLabel)
                    .addComponent(holderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountInformationsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualBalanceLabel)
                    .addComponent(atualBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        accountInformationsPanel.add(accountInformationsContent, java.awt.BorderLayout.CENTER);

        container.add(accountInformationsPanel);

        operationsInAccountPanel.setLayout(new java.awt.GridLayout(2, 0));

        withdrawPanel.setLayout(new java.awt.BorderLayout());

        withdrawHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        withdrawLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        withdrawLabel.setText("Withdraw");
        withdrawHeader.add(withdrawLabel);

        withdrawPanel.add(withdrawHeader, java.awt.BorderLayout.PAGE_START);

        insertAmountLabel.setText("Insert Amount");

        withdrawConfirmBtn.setText("Withdraw");
        withdrawConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawContentLayout = new javax.swing.GroupLayout(withdrawContent);
        withdrawContent.setLayout(withdrawContentLayout);
        withdrawContentLayout.setHorizontalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawContentLayout.createSequentialGroup()
                        .addComponent(insertAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(withdrawConfirmBtn)))
                .addContainerGap())
        );
        withdrawContentLayout.setVerticalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertAmountLabel)
                    .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawConfirmBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        withdrawPanel.add(withdrawContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(withdrawPanel);

        depositPanel.setLayout(new java.awt.BorderLayout());

        depositHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        depositLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositLabel.setText("Deposit");
        depositHeader.add(depositLabel);

        depositPanel.add(depositHeader, java.awt.BorderLayout.PAGE_START);

        depositAmountLabel.setText("Insert Amount");

        depositConfirmBtn.setText("Deposit");
        depositConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositContentLayout = new javax.swing.GroupLayout(depositContent);
        depositContent.setLayout(depositContentLayout);
        depositContentLayout.setHorizontalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositContentLayout.createSequentialGroup()
                        .addComponent(depositAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depositConfirmBtn)))
                .addContainerGap())
        );
        depositContentLayout.setVerticalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAmountLabel)
                    .addComponent(depositAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositConfirmBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        depositPanel.add(depositContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(depositPanel);

        container.add(operationsInAccountPanel);

        Center.add(container);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void withdrawConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawConfirmBtnActionPerformed
        double amount = Double.parseDouble(withdrawAmountTxt.getText());

        try {
            double newBalance = accountService.withdraw(account, bank, amount, bankService);
            refreshAccountInformations(newBalance);
        } catch (InsufficientBalanceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Insuficient Balance Error", JOptionPane.ERROR_MESSAGE);
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Value Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_withdrawConfirmBtnActionPerformed

    private void depositConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositConfirmBtnActionPerformed
        double amount = Double.parseDouble(depositAmountTxt.getText());
        try {
            double newBalance = accountService.deposit(account, bank, amount, bankService);
            refreshAccountInformations(newBalance);
        } catch (InvalidInputException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Value Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_depositConfirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Header;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JTextArea accountIdTxt;
    private javax.swing.JPanel accountInformationsContent;
    private javax.swing.JPanel accountInformationsHeader;
    private javax.swing.JLabel accountInformationsLabel;
    private javax.swing.JPanel accountInformationsPanel;
    private javax.swing.JLabel atualBalanceLabel;
    private javax.swing.JTextArea atualBalanceTxt;
    private javax.swing.JPanel container;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JTextField depositAmountTxt;
    private javax.swing.JButton depositConfirmBtn;
    private javax.swing.JPanel depositContent;
    private javax.swing.JPanel depositHeader;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JLabel holderLabel;
    private javax.swing.JTextArea holderTxt;
    private javax.swing.JLabel insertAmountLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel operationsInAccountPanel;
    private javax.swing.JTextField withdrawAmountTxt;
    private javax.swing.JButton withdrawConfirmBtn;
    private javax.swing.JPanel withdrawContent;
    private javax.swing.JPanel withdrawHeader;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
