/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

/**
 *
 * @author cg3034186
 */
public class EditAccountGUI extends javax.swing.JDialog {

    /**
     * Creates new form EditAccountGUI2
     */
    public EditAccountGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Voltar = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        accountInformationsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        accountIdLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        atualBalanceLabel = new javax.swing.JLabel();
        holderLabel = new javax.swing.JLabel();
        operationsInAccountPanel = new javax.swing.JPanel();
        withdrawPanel = new javax.swing.JPanel();
        withdrawHeader = new javax.swing.JPanel();
        withdraw = new javax.swing.JLabel();
        withdrawContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        withdrawAmountTxt = new javax.swing.JTextField();
        withdrawBtn = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        depositHeader = new javax.swing.JPanel();
        depositLabelHeader = new javax.swing.JLabel();
        depositContent = new javax.swing.JPanel();
        depositAmountLabel = new javax.swing.JLabel();
        depositAmountTxt = new javax.swing.JTextField();
        depositBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        Voltar.setText("Voltar");
        Header.add(Voltar);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Center.setLayout(new java.awt.GridLayout(2, 2));

        container.setLayout(new java.awt.GridLayout());

        accountInformationsPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Account Informations:");
        jPanel1.add(jLabel1);

        accountInformationsPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        accountIdLabel.setText("Account ID:");

        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane2.setEnabled(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        atualBalanceLabel.setText("Atual Balance");

        holderLabel.setText("Holder");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(holderLabel)
                    .addComponent(accountIdLabel)
                    .addComponent(atualBalanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountIdLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holderLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualBalanceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        accountInformationsPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        container.add(accountInformationsPanel);

        operationsInAccountPanel.setLayout(new java.awt.GridLayout(2, 0));

        withdrawPanel.setLayout(new java.awt.BorderLayout());

        withdrawHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        withdraw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        withdraw.setText("Withdraw");
        withdrawHeader.add(withdraw);

        withdrawPanel.add(withdrawHeader, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Insert Amount");

        withdrawBtn.setText("Withdraw");

        javax.swing.GroupLayout withdrawContentLayout = new javax.swing.GroupLayout(withdrawContent);
        withdrawContent.setLayout(withdrawContentLayout);
        withdrawContentLayout.setHorizontalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawContentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(withdrawBtn)))
                .addContainerGap())
        );
        withdrawContentLayout.setVerticalGroup(
            withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(withdrawContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(withdrawAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        withdrawPanel.add(withdrawContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(withdrawPanel);

        depositPanel.setLayout(new java.awt.BorderLayout());

        depositHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        depositLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositLabelHeader.setText("Deposit");
        depositHeader.add(depositLabelHeader);

        depositPanel.add(depositHeader, java.awt.BorderLayout.PAGE_START);

        depositAmountLabel.setText("Insert Amount");

        depositBtn.setText("Deposit");

        javax.swing.GroupLayout depositContentLayout = new javax.swing.GroupLayout(depositContent);
        depositContent.setLayout(depositContentLayout);
        depositContentLayout.setHorizontalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositContentLayout.createSequentialGroup()
                        .addComponent(depositAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depositBtn)))
                .addContainerGap())
        );
        depositContentLayout.setVerticalGroup(
            depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(depositContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAmountLabel)
                    .addComponent(depositAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        depositPanel.add(depositContent, java.awt.BorderLayout.CENTER);

        operationsInAccountPanel.add(depositPanel);

        container.add(operationsInAccountPanel);

        Center.add(container);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditAccountGUI dialog = new EditAccountGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JPanel accountInformationsPanel;
    private javax.swing.JLabel atualBalanceLabel;
    private javax.swing.JPanel container;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JTextField depositAmountTxt;
    private javax.swing.JButton depositBtn;
    private javax.swing.JPanel depositContent;
    private javax.swing.JPanel depositHeader;
    private javax.swing.JLabel depositLabelHeader;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JLabel holderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel operationsInAccountPanel;
    private javax.swing.JLabel withdraw;
    private javax.swing.JTextField withdrawAmountTxt;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JPanel withdrawContent;
    private javax.swing.JPanel withdrawHeader;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
