/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.exceptions.InvalidInputException;
import br.com.bank.model.AccountCurrent;
import br.com.bank.model.Bank;
import br.com.bank.service.AccountService;
import br.com.bank.service.BankService;
import java.awt.Component;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import javax.swing.SwingConstants;

/**
 *
 * @author lucas
 */
public class ListAccountsGUI extends javax.swing.JDialog {

    private final Bank bank;
    private final AccountService accountService;
    private final BankService bankService;

    /**
     * Creates new form ListAccountsGUI
     */
    public ListAccountsGUI(java.awt.Frame parent, boolean modal, Bank bank, AccountService accountService, BankService bankService) {
        super(parent, modal);
        this.bank = bank;
        this.accountService = accountService;
        this.bankService = bankService;

        initComponents();
        getRootPane().registerKeyboardAction(
                e -> dispose(),
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        listAccountsPanel.setLayout(new javax.swing.BoxLayout(listAccountsPanel, javax.swing.BoxLayout.Y_AXIS));

        listAccountsPanel.removeAll();
        try {
            Map<Integer, AccountCurrent> accounts = bankService.listAccounts(bank);
            accounts.forEach((id, account) -> {
                JButton btn = new JButton("Account " + id + " - " + account.getHolder());
                btn.setAlignmentX(Component.LEFT_ALIGNMENT);
                btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, btn.getPreferredSize().height));
                btn.setHorizontalAlignment(SwingConstants.LEFT);
                btn.addActionListener(ev -> {
                    
                });

                listAccountsPanel.add(btn);
                listAccountsPanel.add(Box.createVerticalStrut(8));
            });
        } catch (InvalidInputException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error, The bank is not defined here", JOptionPane.ERROR_MESSAGE);
        }
        listAccountsPanel.revalidate();
        listAccountsPanel.repaint();
        
        voltarBtn.addActionListener(e -> dispose());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        voltarBtn = new javax.swing.JButton();
        conteiner = new javax.swing.JPanel();
        containerHeader = new javax.swing.JPanel();
        searchAccountTxt = new javax.swing.JTextField();
        conteinerContent = new javax.swing.JPanel();
        conteinerScrollList = new javax.swing.JScrollPane();
        listAccountsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List Account");
        setResizable(false);
        setSize(new java.awt.Dimension(480, 360));

        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        voltarBtn.setText("Voltar");
        header.add(voltarBtn);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        conteiner.setLayout(new java.awt.BorderLayout());

        searchAccountTxt.setForeground(new java.awt.Color(120, 120, 120));
        searchAccountTxt.setText("Search Account");
        searchAccountTxt.setPreferredSize(new java.awt.Dimension(390, 26));
        searchAccountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAccountTxtActionPerformed(evt);
            }
        });
        containerHeader.add(searchAccountTxt);

        conteiner.add(containerHeader, java.awt.BorderLayout.PAGE_START);

        listAccountsPanel.setLayout(new javax.swing.BoxLayout(listAccountsPanel, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("jButton1");
        listAccountsPanel.add(jButton1);

        conteinerScrollList.setViewportView(listAccountsPanel);

        javax.swing.GroupLayout conteinerContentLayout = new javax.swing.GroupLayout(conteinerContent);
        conteinerContent.setLayout(conteinerContentLayout);
        conteinerContentLayout.setHorizontalGroup(
            conteinerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conteinerScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        conteinerContentLayout.setVerticalGroup(
            conteinerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conteinerScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        conteiner.add(conteinerContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(conteiner, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchAccountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAccountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAccountTxtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerHeader;
    private javax.swing.JPanel conteiner;
    private javax.swing.JPanel conteinerContent;
    private javax.swing.JScrollPane conteinerScrollList;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel listAccountsPanel;
    private javax.swing.JTextField searchAccountTxt;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
