/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.bank.view;

import br.com.bank.exceptions.InvalidInputException;
import br.com.bank.model.AccountCurrent;
import br.com.bank.model.Bank;
import br.com.bank.service.AccountService;
import java.awt.Component;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class ListAccountsGUI extends javax.swing.JDialog {

    private final Bank bank;
    private final AccountService service;

    /**
     * Creates new form ListAccountsGUI
     */
    public ListAccountsGUI(java.awt.Frame parent, boolean modal, Bank bank, AccountService service) {
        super(parent, modal);
        this.bank = bank;
        this.service = service;

        initComponents();
        getRootPane().registerKeyboardAction(
                e -> dispose(),
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        listContainer.setLayout(new javax.swing.BoxLayout(listContainer, javax.swing.BoxLayout.Y_AXIS));
        javax.swing.JButton bnt = new javax.swing.JButton("Exemplo de conta");

        listContainer.removeAll();
        try {
            Map<Integer, AccountCurrent> accounts = service.listAccounts(bank);
            accounts.forEach((id, account) -> {
                JButton btn = new JButton("Account " + id + " - " + account.getHolder());
                btn.setAlignmentX(Component.LEFT_ALIGNMENT);
                btn.addActionListener(ev -> {
                    
                });

                listContainer.add(btn);
                listContainer.add(Box.createVerticalStrut(8));
            });
        } catch (InvalidInputException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error, The bank is not defined here", JOptionPane.ERROR_MESSAGE);
        }
        listContainer.revalidate();
        listContainer.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List Account");
        setResizable(false);
        setSize(new java.awt.Dimension(480, 360));

        listContainer.setName("listContainer"); // NOI18N
        listContainer.setLayout(new javax.swing.BoxLayout(listContainer, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(listContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listContainer;
    // End of variables declaration//GEN-END:variables
}
